### ISSUE TITLE
Permissive License?

### ISSUE THREAD

**Issue by stephenjlewis** [urbanzrim/stm32-MPU6050#1]
Hey Urban, I'm using the MPU6050 IMU for a project, and your driver is significantly tidier than Invensense's, so I'd love to use your code.

That said, at the moment, this repo doesn't have any licensing notice included, and as such, it remains under full copyright protections and cannot be legally used or modified by me or anyone else.

Would you be willing to release your code under an [MIT license](http://choosealicense.com/licenses/mit/) or something similar? This can be done by adding an appropriate LICENCE file to your repo. 

Thanks for putting this together. Cheers.

**Comment by urbanzrim** [comment]
Hi,

actually the folder is in "living" state. Everything works, but I wanted to
add minor changes for optimal performance. That's why I didn't include
license file yet. I'm planing to do that maybe today or tomorrow (I'm
pretty busy these days).
So that you know for the future, you are welcome to use and modify
everything that is on my github account.
Probably I will use an MIT license or maybe GNU, which is also free.

I'm implementing complementary filter in MPU6050 project right now (it will
be available next week probably) if you are interested.

If you have any questions/proposals, please dont hesitate to contact me.

Best Regards,
Urban Zrim

Lep pozdrav,
Urban Zrim

2015-04-15 1:19 GMT+02:00 Stephen Lewis notifications@github.com:

**Comment by urbanzrim** [comment]
I've added the MIT license in the header files.

BR, Urban Zrim

**Comment by stephenjlewis** [comment]
Thanks Urban; I'll let you know if I have any other suggestions.
